# Generated by Django 3.2.6 on 2021-11-13 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_video_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name_plural': 'Videos'},
        ),
    ]
