# Generated by Django 3.2.6 on 2021-11-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_video_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
