# Generated by Django 3.2.6 on 2021-11-14 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_video_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='slug',
        ),
    ]
